### PR TITLE
Prop integration

### PR DESCRIPTION
**Pull request by courtin**
Added propeller model (fixed weight and radius) to model.

### CODE REVIEW

**Comment by bqpd** [comment]
add to whitelist

**Comment by mjburton11** [comment]
@courtin go ahead and add me as a reviewer in the future when you're ready to merge something

**Comment by mjburton11** [comment]
@courtin what branch do I need to be on in gpkit-models for this to run?

**Comment by mjburton11** [comment]
@courtin let's go ahead and merge the prop model in gplibrary and then once that is passing we can push this one.  Is that possible to do before Monday?

**Comment by courtin** [comment]
@mjburton11 I pushed the changes to the gplibrary prop branch; if you're on that branch the solar model should run now.  I'll submit a pull request to merge that branch

**Comment by mjburton11** [comment]
@courtin prop model looks good! I just reviewed it.  Once those additional changes are in and it's passing tests we'll merge it in.

**Comment by bqpd** [comment]
test this please

**Comment by bqpd** [comment]
test models please

**Comment by courtin** [comment]
This is replaced by https://github.com/convexengineering/solar/pull/26 - closing.

**Pull request closed without merging**
