### PR TITLE
edit abstract for publishing

### PR DESCRIPTION
**Pull request by mjburton11**

### CODE REVIEW

**Comment by mjburton11** [comment]
@bqpd @galbramc this is failing due to a older numpy import that fails on windows... did we ever resolve this with when we had the same issue on `gplibrary`

**Comment by galbramc** [comment]
I'm pretty sure up upgraded numpy to 1.13...

**Comment by mjburton11** [comment]
huh, I wonder why it only fails on windows

**Comment by galbramc** [comment]
Looks like I tried to upgrade, but the upgrade failed for some reason and I didn't notice.

**Comment by galbramc** [comment]
@bqpd, have you upgraded the numpy requirements on gpkit? Is that the right answer here?

**Comment by mjburton11** [comment]
@bqpd it looks like the numpy requirements are `>1.12` right?

**Comment by bqpd** [comment]
yup! on both gplibrary and gpkit

**Comment by mjburton11** [comment]
so what is going on here?

**Comment by mjburton11** [comment]
it looks like it is trying to install 1.11...

**Comment by bqpd** [comment]
test this please

**Comment by bqpd** [comment]
(this first test is gonna take extra long as it installs the new packages)

**Comment by bqpd** [comment]
seems to be working! definitely has a new numpy version

**Comment by mjburton11** [comment]
nice what was the bug?

**Comment by mjburton11** [comment]
and is it a local repo thing or was it a gpkit thing?

**Comment by bqpd** [comment]
windows on Jenkins_ResearchModel was simply missing the lines to update numpy :p

**Comment by mjburton11** [comment]
oh... so if i trigger JHO and gassolar they should pass?

**Comment by bqpd** [comment]
yup!

**Pull request merged**
