### PR TITLE
constrain climb to use only battery power

### PR DESCRIPTION
**Pull request by mjburton11**

### CODE REVIEW

**Comment by mjburton11** [comment]
test this please

**Comment by mjburton11** [comment]
@bqpd Do you know why this is failing? I can't figure it out

**Comment by galbramc** [comment]
mosek is on macys now. The errors are related to not finding expopt.so. I have no idea though why it does not do this only on macys. It works on macys_VM. The only thing I'm worried about is if we are relying on DYLD_* environment variables. Apple has phase those out and using them in any way will not work long term. @bqpd what can I do to help you debug this?

**Comment by bqpd** [comment]
We haven't used DYLD for years, and even fix some of MOSEK's linking errors in 8...could I get a terminal on macys?

**Comment by galbramc** [comment]
@bqpd Yeah I can give you an account. Can you stop by my office tomorrow some time so we can set one up for you?

**Comment by bqpd** [comment]
will do!

**Comment by mjburton11** [comment]
@galbramc @bqpd thanks for taking care of this guys!

**Comment by bqpd** [comment]
test this please

**Comment by mjburton11** [comment]
test this please

**Comment by bqpd** [comment]
@galbramc it's having trouble finding xmlrunner again...
@mjburton11 I'm going to cancel this test and trigger another

**Comment by bqpd** [comment]
test this please

**Comment by bqpd** [comment]
test this please

**Comment by mjburton11** [comment]
@bqpd looks like this failed just because of a time out error?

**Comment by mjburton11** [comment]
test this please

**Pull request merged**
