### PR TITLE
write abstract; setup autogenerated figures; add ability for central fuselage

### PR DESCRIPTION
**Pull request by mjburton11**

### CODE REVIEW

**Comment by bqpd** [comment]
I can't build this because I'm lacking `season.generated.csv`

**Comment by mjburton11** [comment]
test this please

**Comment by mjburton11** [comment]
@bqpd, I don't think this is trying to install `gassolar`. Any ideas?

**Comment by bqpd** [comment]
@mjburton11 I added gpfit to the list of requirements for gassolar, so now TESTCONFIG needs to make sure to install its version of gpfit first: see https://github.com/convexengineering/solar/pull/7

I'm not sure why pip on the jenkins machines couldn't find the gpfit release, but you wouldn't want it to use the one on pip anyway.

**Comment by mjburton11** [comment]
got it. thanks!

**Comment by bqpd** [comment]
let's see how this test goes...

**Pull request merged**
