### PR TITLE
create a bunch of figs

### PR DESCRIPTION
**Pull request by mjburton11**

### CODE REVIEW

**Comment by mjburton11** [comment]
@courtin do you want to add any code you used to generate figs to this?  Can you add it to the `Makefile` too, that way if we change the model it should be easy to regenerate everything

**Comment by courtin** [comment]
yep I can do that

**Comment by mjburton11** [comment]
If you're working on a separate branch, make a PR to merge your branch into this one.  That way all of the figure generating stuff is on the same PR.  Does that make sense?

**Comment by courtin** [comment]
@mjburton11 added propeller count trade plotting function

**Comment by bqpd** [comment]
fig MAKE doesn't run on master right now, and I think it might be a bug..looking into it

**Comment by bqpd** [comment]
fixed, now only tablegen doesn't run...but I'm pretty sure that's a legit unbounded error

since these figures take a long time to make, might be worth considering uploading them?

**Comment by mjburton11** [comment]
Does testing run the Makefile?

**Pull request closed without merging**
