### PR TITLE
relax latitude constraint

### PR DESCRIPTION
**Pull request by mjburton11**
relax latitude constraint to get tests passing

### CODE REVIEW

**Comment by mjburton11** [comment]
@bqpd ok looks like it's not finding the csv files with all of the fitted parameters in gassolar.

**Comment by mjburton11** [comment]
Which I think was just closed in convexengineering/jho#7

**Comment by bqpd** [comment]
hmm, where are you seeing that error? I'm just seeing the same mysterious failure we have elsewhere...at least for the cvxopt machines

**Comment by mjburton11** [comment]
When I open Details and click on the box for macys and mosek I find this error:

`IOError: File /Users/jenkins/workspace/gpkit_ResearchModel_solar_PR/buildnode/macys/optimizer/mosek/venv2_gpkit/lib/python2.7/site-packages/gassolar/environment/windfitsdec/windaltfit_lat1.csv does not exist`

**Comment by bqpd** [comment]
oh, yup. that's on top of the fact that the test reports aren't currently in the correct directory

**Comment by mjburton11** [comment]
Ah good, ok glad I'm not stupid

**Comment by bqpd** [comment]
So I think this shows that gassolar needs to be fixed as in #7. Will create the issue.

**Comment by mjburton11** [comment]
test this please

**Comment by mjburton11** [comment]
Well convexengineering/gassolar#22 seemed to solve the import error problem

**Comment by mjburton11** [comment]
test this please

**Comment by mjburton11** [comment]
test this please

**Pull request merged**
